---
authors:
  - Ansible Network Community (ansible-network)
dependencies:
  "ansible.netcommon": "*"
  "ansible.utils": '*'

license_file: LICENSE
name: base
description: Ansible Network meta Collection to install all network supported content.
namespace: network
readme: README.md
repository: https://github.com/ansible-collections/network.base
issues: https://github.com/ansible-collections/network.base/issue

# NOTE(pabelanger): We create an empty version key to keep ansible-galaxy
# happy. We dynamically inject version info based on git information.
version: null
