---
authors:
  - Rohit Thakur (@rohitthakur2590)
dependencies:
  "ansible.netcommon": "*"
  "ansible.utils": '*'
license_file: LICENSE
name: base
description: Ansible Network Collection provides platform-agnostic resource management for given network OS.
namespace: network
readme: README.md
repository: https://github.com/redhat-cop/network.base
issues: https://github.com/redhat-cop/network.base/issues
version: 1.2.0
