---
- name: Run the platform facts module
  ansible.netcommon.network_resource:
    os_name: "{{ ansible_network_os }}"
    name: "{{ ansible_network_os }}_{{ item }}"
    state: gathered
  register: result

- debug:
    msg: "{{ result }}"
  when:
    - action != 'persist'

- include: includes/write_to_file.yaml
  when:
    - action == 'persist'
    - result["gathered"] != {}
    - result["gathered"] != []
