---
- name: Run the platform facts module
  ansible.netcommon.network_resource:
    os_name: "{{ ansible_network_os }}"
    name: "{{ ansible_network_os }}_{{ res }}"
    state: gathered
  register: resource_manager_result

- name: Resource Facts
  ansible.builtin.debug:
    msg: "{{ resource_manager_result }}"
  when:
    - operation != 'persist'

- name: Include file write task
  ansible.builtin.include_tasks: includes/write_to_file.yaml
  when:
    - operation == 'persist'
    - ignore_empty is undefined
    - resource_manager_result["gathered"] != {}
    - resource_manager_result["gathered"] != []

- name: Include file write task
  ansible.builtin.include_tasks: includes/write_to_file.yaml
  when:
    - operation == 'persist'
    - ignore_empty is defined
