---
- name: Set default path
  ansible.builtin.set_fact:
    inventory_directory: "."
  when: origin is defined

- name: Retrieve a repository from a distant location and make it available locally
  ansible.builtin.include_tasks: includes/retrieve.yaml
  when: origin is defined 

- name: Include file write task
  ansible.builtin.include_tasks: includes/inventory.yaml

# - name: Set default path
#   ansible.builtin.set_fact:
#     inventory_directory: "."
#   when: inventory_directory is not defined

- name: Get list of files
  ansible.builtin.find:
    paths: "{{ inventory_path }}/host_vars/{{ inventory_hostname }}"
    recurse: false
    patterns: "*.yaml"
    file_type: file
  register: found_directories

- name: Include configure task
  ansible.builtin.include_tasks: includes/configure.yaml
  loop: "{{ found_directories.files }}"
  loop_control:
    label: "{{ item.path | basename }}"
