---
- name: Apply provided configuration
  ansible.netcommon.network_resource:
    os_name: "{{ ansible_network_os }}"
    name: "{{ ansible_network_os.split('.')[-1] }}_{{ resource_manager_lst }}"
    config: "{{ module_vars[resource_manager_resource] }}"
    state: "{{ resource_manager_state }}"
  when:
    - resource_manager_lst in resources
    - module_vars[resource_manager_resource]
