---
- name: Publish the persist changes
  ansible.scm.git_publish:
    path: "{{ repository['path'] }}"
    timeout: 120
  when: token is undefined

- name: Publish the changes
  ansible.scm.git_publish:
    path: "{{ repository['path'] }}"
    token: "{{ token }}"
    timeout: 120
  when: token is defined
