---
- name: Retrieve a repository from a distant location and make it available locally
  ansible.scm.git_retrieve:
    origin:
      url: "{{ origin }}"
    parent_directory: "{{ inventory_directory }}"
  register: repository