---
- name: Retrieve a repository from a distant location and make it available locally
  ansible.scm.git_retrieve:
    origin:
      url: "{{ origin }}"
      token: "{{ token }}"
    timeout: 120
    parent_directory: "{{ inventory_directory }}"
  when: token is defined
  register: repository

- name: Retrieve a repository from a distant location and make it available locally
  ansible.scm.git_retrieve:
    origin:
      url: "{{ origin }}"
    timeout: 120
    parent_directory: "{{ inventory_directory }}"
  register: repository
  when: token is undefined
