---
- name: Set default path
  ansible.builtin.set_fact:
    inventory_directory: ./inventory
  when: inventory_directory is not defined

- name: Create inventory directory
  ansible.builtin.file:
    path: "host_vars/{{ inventory_hostname }}"
    state: directory

- name: Write each resource to a file
  ansible.builtin.copy:
    content: "{{ {item: result['gathered']} | to_nice_yaml }}"
    dest: "host_vars/{{ inventory_hostname }}/{{ item }}.yaml"
    mode: '644'
  when:
    - result['gathered'] != {}
    - result['gathered'] != []

- name: Write each empty resource to a file
  ansible.builtin.copy:
    content: "{{ item }}:"
    dest: "host_vars/{{ inventory_hostname }}/{{ item }}.yaml"
    mode: '644'
  when:
    - result['gathered'] == {} or result['gathered'] == []
    - persist_empty is true
