---
- name: Create inventory directory
  ansible.builtin.file:
    path: "{{ resource_manager_inventory_path }}/host_vars/{{ inventory_hostname }}"
    state: directory
    mode: '0755'

- name: Write each resource to a file
  ansible.builtin.copy:
    content: "{{ {res: resource_manager_result['gathered']} | to_nice_yaml }}"
    dest: "{{ resource_manager_inventory_path }}/host_vars/{{ inventory_hostname }}/{{ res }}.yaml"
    mode: '0755'
