---
- name: Create inventory directory
  ansible.builtin.file:
    path: "{{ inventory_path }}/host_vars/{{ inventory_hostname }}"
    state: directory
    mode: '644'

- name: Write each resource to a file
  ansible.builtin.copy:
    content: "{{ {item: result['gathered']} | to_nice_yaml }}"
    dest: "{{ inventory_path }}/host_vars/{{ inventory_hostname }}/{{ item }}.yaml"
    mode: '644'
